### ISSUE TITLE
PSR Complience

### ISSUE THREAD

**Issue by GrahamCampbell** [nette/code-checker#23]
Would you accept a pull to move us over to PSR-2 with PSR-4?

**Comment by dg** [comment]
Thank you, but no, I am using tabulators.

**Comment by fprochazka** [comment]
@GrahamCampbell symfony has such a tool. Why not just use that?

**Comment by GrahamCampbell** [comment]
@fprochazka I know. I maintain https://styleci.io/ and have written quite a few fixers for that tool. :)
