### ISSUE TITLE
Code-checker is useless for files indent only by spaces

### ISSUE THREAD

**Issue by ZZromanZZ** [nette/code-checker#27]
Since version >=2.6 

Caused by this [commit](https://github.com/nette/code-checker/commit/99597dd908cac8eb1a04683c823fad59ec83a1e0), I guess.

**Comment by JanTvrdik** [comment]
That's probably intentionally.

**Comment by dg** [comment]
It is intentional because Nette uses only tabs.

**Comment by ZZromanZZ** [comment]
I understand, but there is no need to use it only for Nette.

Why so strict, a command line switch switching between tab, spaces, or 
skipping test completely, would be useful.

**Comment by dg** [comment]
It certainly is, but I don't want to develop a tool for others. So feel free to fork it and make it better.
