### ISSUE TITLE
whitespaces check

### ISSUE THREAD

**Issue by t0his** [nette/code-checker#28]
Check can report [FOUND] 0 bytes of whitespaces if there is missing EOL at the end of file and there is 1 whitespace on empty line.

**Comment by JanTvrdik** [comment]
And what is expected behavior?

**Comment by t0his** [comment]
Either the last line is required and then check for it and report it missing. Or dont add the line to the file in the whitespaces check.

**Comment by dg** [comment]
Can you fix it?
