### ISSUE TITLE
Mixed tabs and spaces indentation when scanning whole directory

### ISSUE THREAD

**Issue by foxycode** [nette/code-checker#31]
- bug report? yes
- feature request? no
- version: 2.6 - 2.8

Since version 2.6, I see error `Mixed tabs and spaces indentation` in lot of files. I checked carefully and there definitely isn't any tab at all, just spaces. Everything is working great on all projects with version 2.5.

I tried to run new version with single file and it's working great, but not with `-d` parameter on whole folder, even if there is only one file in that folder. Also trid php 5.6, 7.0 and 7.1. Result is same for all versions. I am using Ubuntu 16.04 and PHP from Ondřej Surý PPA.

```bash
$ php7.0 temp/code-checker/src/code-checker.php --short-arrays -d app/Router

CodeChecker version 2.8
-----------------------
Running in read-only mode
Scanning /home/app/Router
[ERROR]   RouterFactory.php:10    Mixed tabs and spaces indentation
Done.                                   

$ php7.0 temp/code-checker/src/code-checker.php --short-arrays -d app/Router/RouterFactory.php 

CodeChecker version 2.8
-----------------------
Running in read-only mode
Scanning /home/app/Router/RouterFactory.php
Done.
```

and RouterFactory:
```php
<?php

namespace App\Router;

use Nette\Application\Routers\Route;
use Nette\Application\Routers\RouteList;

final class RouterFactory
{
    /**
     * @return RouteList
     */
    public static function createRouter()
    {
        Route::$defaultFlags = Route::SECURED;

        $router = new RouteList();

        $router[] = new Route('/AM/image.php?id=<id \d+>', 'BannerImage:default');
        $router[] = new Route('/sk/AM/image.php?id=<id \d+>', 'BannerImage:default');
        $router[] = new Route('/<presenter>/<action>[/<id>]', 'Homepage:default');

        return $router;
    }
}
```

**Comment by dg** [comment]
Can you suggest better error message?

**Comment by foxycode** [comment]
@dg First, I don't know where is problem. File seems ok. There aren't any tabs at all. I believe this is code-checker bug.

**Comment by dg** [comment]
But there are spaces, yes?

**Comment by foxycode** [comment]
@dg Yes, but *only* spaces. An it's working great with 2.5. You added check that only tabs are alloed?

**Comment by dg** [comment]
Yes, only tabs are allowed. PHP file with only spaces and no tab is simply wrong.

**Comment by foxycode** [comment]
@dg Ok, I understand this is tool for checking Nette code. But I don't use tabs in my projects (I go with PSR) and it worked for me until 2.6. What about adding some console switch to allow spacess too?

**Comment by dg** [comment]
Simply fork this tool.

**Comment by foxycode** [comment]
If I do it and send PR, will you accept?

**Comment by dg** [comment]
This is simple tool for checking my projects, I dont want to have switch option for everything.

**Comment by foxycode** [comment]
Ok, closing.
