### ISSUE TITLE
CI - show affected rows

### ISSUE THREAD

**Issue by f3l1x** [nette/code-checker#34]
- bug report? no
- feature request? yes
- version: 2.10.0

### Description

If nette/code-check finds an error it shows:

```
[FOUND]   cs/mailing.texy    1 bytes of whitespaces
[FOUND]   en/mailing.texy    1 bytes of whitespaces
```

It's very complicated to find the trailing bytes without installing of checker. Let's think about some row hints?  

```
[FOUND]   cs/mailing.texy    1 bytes of whitespaces on line 123
[FOUND]   en/mailing.texy    3 bytes of whitespaces on line 124, 135, 144
```

WDYT?

**Comment by dg** [comment]
The best way is to install Checker and let him fix it. You would not do it manually :)

**Comment by f3l1x** [comment]
Yes, you're right. Although, add any verbose option `codechecker -v` would make me happier ;-)

**Comment by DanielRuf** [comment]
Bump.
Or a diff / dry run option.
