### ISSUE TITLE
Check multiple files/folders (feature)

### ISSUE THREAD

**Issue by pupitooo** [nette/code-checker#36]
- bug report? no
- feature request? yes
- version: 3.1.1 

### Description
It would be nice to be able to check more files. Not only one file/folder, but add more files/folders to check. I miss behaviour like [coding-standard](https://github.com/nette/coding-standard) has.

**Comment by dg** [comment]
Can you try to implement it?

**Comment by pupitooo** [comment]
Děkuji uctivě!

**Comment by pupitooo** [comment]
I use this in pre-commit hook, so it would be better to accept parameters in same way as coding-standars do. But I used `sed` to add more files with `-d` option.

But in previous version coding-checker accepted folder [or files](https://github.com/nette/code-checker/issues/19).

Please, can you improve it again for accepting multiple files too?

**Comment by dg** [comment]
fixed

**Comment by pupitooo** [comment]
Again...thank you a lot.
